import os

env = Environment(ENV=os.environ)

QFT_INC = os.environ['QFT_PATH'] + '/include'
QFT_LIB = os.environ['QFT_PATH'] + '/lib'

MINT = os.environ['MINT2'] + '/'
MINT_LIB = MINT + 'lib/'

env.Append(CPPPATH = ['.', QFT_INC, MINT])
env.Append(CXXFLAGS = ['-O3', '-Wall', '-Wextra', '-Werror', '-pedantic', '-std=c++11', '-fopenmp'])
#env.Append(CXXFLAGS = ['-g', '-Wall', '-Wextra', '-Werror', '-pedantic', '-std=c++11', '-fopenmp'])
env.ParseConfig("root-config --libs --cflags --ldflags")
env.Append(LIBPATH = [QFT_LIB, MINT_LIB])
env.Append(LIBS = ['Minuit2', 'MathMore', 'qft++', 'Mint2'])
env.Append(LINKFLAGS = ['-fopenmp'])

#Export environment
Export('env')

#Run SConscript files
SConscript('SConscript')
